apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: application
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30900
      protocol: TCP
    - name: console
      port: 39765
      targetPort: 39765
      nodePort: 30965
      protocol: TCP
