apiVersion: v1
kind: Pod
metadata:
  name: data-service
  namespace: application
  labels:
    app: data-service
spec:
  serviceAccountName: data-service-sa
  containers:
  - name: awscli
    image: amazon/aws-cli
    command: ["sleep", "3600"]
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio-secret
          key: accesskey
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-secret
          key: secretkey
    - name: AWS_DEFAULT_REGION
      value: "us-east-1"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
  restartPolicy: Never
