apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: application
spec:
  selector:
    app: data-service
  ports:
    - port: 5678
      targetPort: 5678
  type: ClusterIP  # Internal only

